// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGoo2lYCKlTQZq-q9Wx3SzR5ljtEBJfRY',
    appId: '1:168222984802:web:0398dfac91b432cca75f3b',
    messagingSenderId: '168222984802',
    projectId: 'banaonotesapp',
    authDomain: 'banaonotesapp.firebaseapp.com',
    storageBucket: 'banaonotesapp.appspot.com',
    measurementId: 'G-4BV5GT5XMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2JZY1BQhJDJtQJsscNK2Ph5SY2adktjQ',
    appId: '1:168222984802:android:d7315308c7265cf9a75f3b',
    messagingSenderId: '168222984802',
    projectId: 'banaonotesapp',
    storageBucket: 'banaonotesapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4nMAt1qZ5achLEJXGi4kgMem-g4jPK8k',
    appId: '1:168222984802:ios:b5849353d2eec8e5a75f3b',
    messagingSenderId: '168222984802',
    projectId: 'banaonotesapp',
    storageBucket: 'banaonotesapp.appspot.com',
    iosBundleId: 'com.example.banaoNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4nMAt1qZ5achLEJXGi4kgMem-g4jPK8k',
    appId: '1:168222984802:ios:fa61ab87d23137b2a75f3b',
    messagingSenderId: '168222984802',
    projectId: 'banaonotesapp',
    storageBucket: 'banaonotesapp.appspot.com',
    iosBundleId: 'com.example.banaoNotesApp.RunnerTests',
  );
}
